configs/modules/core/estimation/mperson_smpl_estimator.py
configs/shape_aware_3d_pose_optim/shape_aware_3d_pose_optimizer.py
docs/en/apis.md
docs/en/tools/mview_mperson_smplify3d.md
tools/mview_mperson_smplify3d.py
xrmocap/core/estimation/builder.py
xrmocap/core/estimation/mperson_smpl_estimator.py
xrmocap/core/estimation/mview_mperson_end2end_estimator.py
xrmocap/core/estimation/mview_mperson_topdown_estimator.py
xrmocap/io/image.py

1. Class MultiViewMultiPersonTopDownEstimator, for MVPose inference. Triangulation and assemble keypoints3d are still not completed.
2. Class MultiViewMultiPersonEnd2EndEstimator, for MvP inference. Forward of MvP model is not completed.

[Feature] Add structures for mview mperson kps3d/smpl estimator

---

docs/en/getting_started.md
docs/en/tools/process_smc.md
tools/process_smc.py

1. Fix mistakes in getting_started and tools docs
2. Rename output of process_smc tool, remove suffix `.smc`

[Fix] fix mistakes for mview sperson

---

configs/modules/core/estimation/mview_mperson_topdown_estimator.py
configs/modules/ops/triangulation/reprojection_error_point_selector.py
tests/ops/test_reprojection_error_point_selector.py
xrmocap/core/estimation/mview_mperson_topdown_estimator.py
xrmocap/ops/top_down_association/mvpose_associator.py
xrmocap/ops/triangulation/point_selection/builder.py
xrmocap/ops/triangulation/point_selection/reprojection_error_point_selector.py

- add reprojection error point selector
- fix `sframe_association_results` with new people enter

[Feature] reprojection error point selector

---

configs/mvp/campus_config/mvp_campus.py
configs/mvp/panoptic_config/mvp_panoptic.py
configs/mvp/panoptic_config/mvp_panoptic_3cam.py
configs/mvp/shelf_config/mvp_shelf.py
configs/mvp/shelf_config/mvp_shelf_50.py
docs/en/getting_started.md
docs/en/tools/eval_model.md
docs/en/tools/train_model.md

1. Rearranged the file structure for training data, testing data, and pretrained weights.
2. Updated the tutorials and added detailed instructions on the `Getting Started` page.
3. Updated the config files for easier starting. Avoided renaming downloaded files.

[Fix ] Update docs and tutorials for MvP training and evaluation

---

.github/workflows/build.yml
configs/modules/core/estimation/mview_mperson_topdown_estimator.py
configs/modules/core/evaluation/mview_mperson_eval_shelf_unittest.py
configs/modules/ops/top_down_association/mvpose_associator.py
configs/modules/ops/top_down_association/mvpose_tracking_associator.py
configs/mvpose/README.md
configs/mvpose/campus_config/eval_keypoints3d.py
configs/mvpose/mview_mperson_topdown_estimator.py
configs/mvpose/panoptic_config/eval_keypoints3d.py
configs/mvpose/shelf_config/eval_keypoints3d.py
configs/mvpose_tracking/README.md
configs/mvpose_tracking/campus_config/eval_keypoints3d.py
configs/mvpose_tracking/mview_mperson_topdown_estimator.py
configs/mvpose_tracking/panoptic_config/eval_keypoints3d.py
configs/mvpose_tracking/shelf_config/eval_keypoints3d.py
docs/en/getting_started.md
scripts/download_weight.sh

- Updated the config files for easier starting.

[Doc] Update mvpose docs

---

.github/workflows/lint.yml
xrmocap/data_structure/body_model/smpl_data.py
xrmocap/data_structure/body_model/smplx_data.py

1. Fix wrong batch_size error caused by SMPLXData's body_pose
2. Fix wrong data dtype error caused by to_tensor_dict

[Fix] fix SMPL(X/XD)Data

---

configs/mvp/campus_config/mvp_campus.py
configs/mvp/panoptic_config/mvp_panoptic.py
configs/mvp/panoptic_config/mvp_panoptic_3cam.py
configs/mvp/shelf_config/mvp_shelf.py
configs/mvp/shelf_config/mvp_shelf_50.py
xrmocap/core/evaluation/mvp_evaluation.py
xrmocap/core/train/__init__.py
xrmocap/core/train/trainer.py
xrmocap/utils/mvp_utils.py

1. Refactor evaluation for learning-based methods
2. Fix file saving for predicted keypoints3d during the evaluation with multiple GPUs

[Add] Refactor evaluation for learning-based methods

---

docs/en/dataset_preparation.md

Update links to tools in the data preparation tutorial

[Fix] Update links in the tutorial

---

xrmocap/transform/keypoints3d/optim/builder.py
xrmocap/transform/keypoints3d/optim/prior_optimizer.py

1. Add 3D bbox constraint optimizer
2. Add limb length constraint optimizer

[Add] Add human prior optimizer for 3D keypoints

---

docs/en/installation.md
docs/en/tools/mmdeploy.md
tools/process_smc.py

1. add SMPLifyx support in process_smc tool, smplx_data will be dumped and visualized
2. update installation.md, add mmdeploy installation guide and update torch version to 1.12.0

[Feature] add SMPLifyx support in process_smc tool

---

xrmocap/core/visualization/visualize_smpl.py
xrmocap/data_structure/body_model/smpl_data.py

update version
1. Fix the correspondence of mask's batchsize in `smpl_data.py`.
2. Fix running long-time video-writing running in `visualize_smpl.py`. Fix the absence of `images_to_video` function

[Fix] Fix bug in visualize_smpl and smpl data

---

README.md
configs/modules/core/evaluation/mview_mperson_eval_shelf_unittest.py
configs/mvpose/campus_config/eval_keypoints3d.py
configs/mvpose/panoptic_config/eval_keypoints3d.py
configs/mvpose/shelf_config/eval_keypoints3d.py
configs/mvpose_tracking/campus_config/eval_keypoints3d.py
configs/mvpose_tracking/panoptic_config/eval_keypoints3d.py
configs/mvpose_tracking/shelf_config/eval_keypoints3d.py
tools/visualize_dataset.py
xrmocap/core/evaluation/metrics/pa_mpjpe_metric.py
xrmocap/core/evaluation/metrics/pcp_metric.py
xrmocap/core/evaluation/top_down_association_evaluation.py
xrmocap/utils/mvpose_utils.py

refactor evaluation for mvpose and mvpose_tracking

[Refactor] refactor evaluation for mvpose and mvpose_tracking

---

xrmocap/model/registrant/smplify.py

Related to https://github.com/openxrlab/xrmocap/issues/85

[Fix] Fix betas error according to issues_85

---

configs/mvp/README.md
configs/mvp/panoptic_config/mvp_panoptic.py
configs/mvp/panoptic_config/mvp_panoptic_3cam.py

1. Add docs for changes in evaluation results
2. Update full benchmark results for MvP

[Add] update benchmarks and docs for MvP

---

.github/workflows/build.yml
.github/workflows/lint.yml

Github ubuntu-18.04 runner is deprecated, update to ubuntu-20.04

[Fix] Workflow runner update

---

.gitignore

Remove mmhuman3d as a submodule

[Fix] Remove mmhuman3d as submodule

---

tests/data_structure/body_model/test_smplxd_data.py
tests/model/registrant/test_smplifyxd.py
xrmocap/data_structure/body_model/smplxd_data.py

Fix the bug reported by https://github.com/openxrlab/xrmocap/issues/109.

[Fix] Fix wrong displacement shape mentioned by issue

---

docs/en/changelog.md
xrmocap/version.py

Simplified the content of changelog.md, only showing important updates in changelog.md. For the full update description of each version, please refer to the release notes.

[Version] Bump to version 0.8.0

---

docs/en/getting_started.md
docs/en/tools/process_smc.md

[Fix] Update download link for example raw .smc file

---

tools/mview_mperson_end2end_estimator.py
xrmocap/transform/keypoints3d/optim/rm_duplicate.py

1. Fix the bug mentioned in #111 caused by the number of tracklet not aligning with the total number of persons during keypoints optimization
2. Update visualization in `mview_mperson_end2end_estimator`

[Fix] Num of tracklet does not align

---

docs/en/tools/prepare_dataset.md
docs/en/tools/visualize_dataset.md
requirements/build.txt

Fix https://github.com/openxrlab/xrmocap/issues/138

[Fix] Fix config paths in doc
